### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by QuasarX** [p512/TeamSpeak-Formatting#1]
Please add this features;
**1. Bold text
2. Italic text
3. Underlined text
4. Limit text lenght : 1024** (Teamspeak not allowed higher value than 1024)

**Comment by ambiso** [comment]
I haven't looked into this project for quite a while, and looking back on it the code seems like a huge mess.
Either way, going to see what I can do to refactor it or start anew.

**Comment by ambiso** [comment]
Well the new version is there to use, however I was unable to compile v8 on windows so far therefore no release yet.
