### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Bluscream** [p512/TeamSpeak-Formatting#2]
Could you provide a compiled release?
People are asking for it (https://r4p3.net/threads/release-text-formatting-application.480/post-50926)

**Comment by ambiso** [comment]
I'll look into it this evening. I didn't manage to compile it on windows last time I tried so there may only be a linux version. :)

**Comment by Bluscream** [comment]
Atleast something to start :) I can try to provide a windows release for you

**Comment by ambiso** [comment]
So I've rewritten it as a web application since I don't see any reason it should be a compiled binary. 

For now it only supports the rainbow mode and doesn't do any attempts at compressing the text.
You can fork and pull request or I can add you as a contributor if you feel like adding to it!
